import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText


def send_email(html_content):
    # Set up the SMTP server
    server = smtplib.SMTP('mailgate.uswc.uswest.com', 25)  # Gmail's SMTP server

    # Create the email message
    msg = MIMEMultipart()
    msg['From'] = "epwfbatch@centurylink.com"  # replace with your Gmail address
    msg[
        'To'] = "TeamPayOneA2@lumen.com, TeamPayTwo@lumen.com, pmt_system_fallout@lumen.com, PMT_SYS_NOTIFICATION@lumen.com, EPWFPROD@lumen.com"
    # msg['To'] = "Test-Email@lumen.com"
    msg['Subject'] = "EPWF Fallout Analysis Report - Autogenerated Email"

    # Attach the HTML content to the email
    msg.attach(MIMEText(html_content, 'html'))

    # Send the email
    server.send_message(msg)
    print("Email sent successfully")
    server.quit()


def send_email_for_update_queries():
    # Read the update queries from the file
    with open('../update_queries.txt', 'r') as file:
        update_queries = file.read()

    # Set up the SMTP server
    server = smtplib.SMTP('mailgate.uswc.uswest.com', 25)  # Gmail's SMTP server

    # Create the email message
    msg = MIMEMultipart()
    msg['From'] = "epwfbatch@centurylink.com"  # replace with your Gmail address
    msg['To'] = "Girish.M@lumen.com, Emmanuel.Bandi@lumen.com, Vikas.Sharma@lumen.com, TeamPayOneA2@lumen.com"
    # msg['To'] = "Test-Email@lumen.com"
    msg['Subject'] = "Update Queries for Production - Autogenerated Email"

    # Attach the update queries to the email
    msg.attach(MIMEText(update_queries, 'plain'))

    # Send the email
    server.send_message(msg)
    print("Update queries Email sent successfully")
    server.quit()


def send_cpe_email(file_path):
    # Set up the SMTP server
    server = smtplib.SMTP('mailgate.uswc.uswest.com', 25)  # Gmail's SMTP server

    # Create the email
    msg = MIMEMultipart()
    msg['From'] = "epwfbatch@centurylink.com"  # replace with your Gmail address
    msg['To'] = "anvesh.kashyap@lumen.com"
    msg['Subject'] = "CPE data for Production - Autogenerated Email"

    # Attach the content of the file to the email
    with open(file_path, 'r') as file:
        msg.attach(MIMEText(file.read()))

    # Send the email
    server.send_message(msg)
    print("CPE Email sent successfully")
    server.quit()
